setwd('./pictures')
png('test.png')
limit<-c(min(test.pko$price/median(test.pko$price), test.kghm$price/median(test.kghm$price)), max(test.pko$price/median(test.pko$price), test.kghm$price/median(test.kghm$price)))
plot(test.pko$time, test.pko$price/median(test.pko$price), pch=20, col='red', ylim=limit)
points(test.kghm$time, test.kghm$price/median(test.kghm$price), pch=20)
dev.off()
setwd('./..')

#test
plot(data.0[[1]]$time, data.0[[1]]$price, pch=20, col=rgb(0,0,0, alpha=.1))

#wykresy cen na danych z 19 feb
setwd('./pictures')
png('00_FEB19.png')
par(mfcol=c(2,2))
plot(data.0[[1]]$time, data.0[[1]]$price, pch=20, col=rgb(0,0,0, alpha=.1), xlab='Time', ylab='Price (PLN)', main='KGHM prices on February 19, 2014.')
plot(data.0[[2]]$time, data.0[[2]]$price, pch=20, col=rgb(0,0,0, alpha=.1), xlab='Time', ylab='Price (PLN)', main='PKO prices on February 19, 2014.')
plot(data.0[[3]]$time, data.0[[3]]$price, pch=20, col=rgb(0,0,0, alpha=.1), xlab='Time', ylab='Price (PLN)', main='PGE prices on February 19, 2014.')
plot(data.0[[4]]$time, data.0[[4]]$price, pch=20, col=rgb(0,0,0, alpha=.1), xlab='Time', ylab='Price (PLN)', main='PZU prices on February 19, 2014.')
dev.off()
setwd('./..')



#h 1-min  19 feb
setwd('./pictures')
png('1_min_FEB19.png')
par(mfcol=c(2,2))
plot(data.01[[1]][['time.p']], data.01[[1]][['p']], xlab='Time', ylab='Price (PLN)', main='1-minute KGHM prices on February 19, 2014.')
plot(data.01[[3]][['time.p']], data.01[[3]][['p']], xlab='Time', ylab='Price (PLN)', main='1-minute PKO prices on February 19, 2014.')
plot(data.01[[5]][['time.p']], data.01[[5]][['p']], xlab='Time', ylab='Price (PLN)', main='1-minute PGE prices on February 19, 2014.')
plot(data.01[[7]][['time.p']], data.01[[7]][['p']], xlab='Time', ylab='Price (PLN)', main='1-minute PZU prices on February 19, 2014.')
dev.off()
setwd('./..')

#10-min  7 Jul
setwd('./pictures')
png('1_min_JUL07.png')
par(mfrow=c(2,2))
plot(data.10[[2]][['time.p']], data.10[[2]][['p']], xlab='Time', ylab='Price (PLN)', main='10-minute KGHM prices on July 7, 2014.')
plot(data.10[[4]][['time.p']], data.10[[4]][['p']], xlab='Time', ylab='Price (PLN)', main='10-minute PKO prices on July 7, 2014.')
plot(data.10[[6]][['time.p']], data.10[[6]][['p']], xlab='Time', ylab='Price (PLN)', main='10-minute PGE prices on July 7, 2014.')
plot(data.10[[8]][['time.p']], data.10[[8]][['p']], xlab='Time', ylab='Price (PLN)', main='10-minute PZU prices on July 7, 2014.')
dev.off()
setwd('./..')
par(mfrow=c(1,1))

# 1-min  19 feb
setwd('./pictures')
png('1_min_FEB19.png')
par(mfcol=c(2,2))
plot(data.01[[1]][['time.r']], data.01[[1]][['r']]*100, xlab='Time', ylab='Return (%)', main='1-minute KGHM prices on February 19, 2014.')
abline(h=0)
plot(data.01[[3]][['time.r']], data.01[[3]][['r']]*100, xlab='Time', ylab='Return (%)', main='1-minute PKO prices on February 19, 2014.')
abline(h=0)
plot(data.01[[5]][['time.r']], data.01[[5]][['r']]*100, xlab='Time', ylab='Return (%)', main='1-minute PGE prices on February 19, 2014.')
abline(h=0)
plot(data.01[[7]][['time.r']], data.01[[7]][['r']]*100, xlab='Time', ylab='Return (%)', main='1-minute PZU prices on February 19, 2014.')
abline(h=0)
dev.off()
setwd('./..')
#w 10-min  7 Jul
setwd('./pictures')
png('1_min_JUL07.png')
par(mfrow=c(2,2))
plot(data.10[[2]][['time.r']], data.10[[2]][['r']]*100, xlab='Time', ylab='Return (%)', main='10-minute KGHM prices on July 7, 2014.')
abline(h=0)
plot(data.10[[4]][['time.r']], data.10[[4]][['r']]*100, xlab='Time', ylab='Return (%)', main='10-minute PKO prices on July 7, 2014.')
abline(h=0)
plot(data.10[[6]][['time.r']], data.10[[6]][['r']]*100, xlab='Time', ylab='Return (%)', main='10-minute PGE prices on July 7, 2014.')
abline(h=0)
plot(data.10[[8]][['time.r']], data.10[[8]][['r']]*100, xlab='Time', ylab='Return (%)', main='10-minute PZU prices on July 7, 2014.')
abline(h=0)
dev.off()
setwd('./..')
par(mfrow=c(1,1))